name: build

on:
    push:
        branches:
            - main

jobs:
    build:
        name: build
        runs-on: ubuntu-latest
        steps:
            -
                name: Set up Go
                uses: actions/setup-go@v3
                with:
                        go-version: '>=1.17.0'
            -
                name: Check out code
                uses: actions/checkout@v3
            -
                name: Build
                run: go build -v .
                working-directory: cmd/signotifi3r/